### ISSUE TITLE
Cannot customize the failed unlock attempt counter

### ISSUE THREAD

**Issue by LunarEclipse363** [Raymo111/i3lock-color#128]
## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (a missing feature)
</pre>

## Current Behavior

There's no way to change the font, text size, position, string or color of the failed unlock counter (you can enable it using the `-f` or `--show-failed-attempts` flag).

## Expected Behavior

Ability to use flags to customize aforementioned things, like with for example time display.

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.12.c-non-git © 2010 Michael Stapelberg, © 2015 Cassandra Fox
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (i3lock-color)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by PandorasFox** [comment]
`--wrongpos`, `--wrongfont`, etc. are already implemented.

**Comment by LunarEclipse363** [comment]
These options are for the "wrong" text though, I meant the options for the failed attempts counter which you can enable using the `-f` flag.
I tested it more now and only `--wrongcolor` and `--wrongfont` affect it. It's position and font size stay the same regardless of the `--wrongpos`, `--wrongsize` flags, also there's no way to change it from simply a number to for example "Failed: x" where x is the number of failed unlock attempts like you can do with for example the clock.

**Comment by PandorasFox** [comment]
it's been a while, so my above comment was a bit inaccurate - the failed text is rendered in the status_text object as just a different string, with some settings overridden / some inherited. This is mostly intended (though there is a todo: [here](https://github.com/PandorasFox/i3lock-color/blob/master/unlock_indicator.c#L799-L810) that should be cleaned up at some point. (As an aside - the STATE_I3LOCK_LOCK_FAILED is for when i3lock fails to grab the keyboard/mouse and isn't for failed unlock attempts). It looks like that at some point in a refactor, the setting of wrongpos was dropped from [here](https://github.com/PandorasFox/i3lock-color/blob/master/unlock_indicator.c#L971-L974) - it should check if there's >0 failed attempts and failed attempts are shown and override .x and .y with the wrong_x and wrong_y.

The string likely won't ever allow for much customization for a handful of reasons.

I'm waiting on approval from company lawyers before I actually commit any code to this project again so that its copyright isn't justified; as soon as that is done I'll write the patch for this. My apologies for not looking more closely at this.

**Comment by Raymo111** [comment]
@PandorasFox What's with the company lawyers thing?
