### ISSUE TITLE
Short keyboard layout

### ISSUE THREAD

**Issue by Rizhiy** [Raymo111/i3lock-color#186]
##  This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

There is no option to use 2 letter language code
## Expected Behavior

Add option (e.g. `--keylayout 3`) that will display keyboard layout using 2 letter code

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.12.c.5 © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2020 Raymond Li
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[x] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment]
Sorry for taking so long to reply. I just tackled a bug with `--keylayout 2` (memory leak) and pushed it into the latest release. I thought `--keylayout 2` was the 2-letter code?

**Comment by Rizhiy** [comment]
It isn't for me.
Here is `--keylayout 1`:
![IMG_20201224_034350](https://user-images.githubusercontent.com/5617397/103046772-7a0ec300-459a-11eb-8b66-76638680c562.jpg)
Here is `--keylayout 2`:
![IMG_20201224_034406](https://user-images.githubusercontent.com/5617397/103046816-a0ccf980-459a-11eb-9c74-0744c2c8891f.jpg)
Unfortunately, both of them use "Russian" for Russian.

Ideally, I would like "UK" or "GB" for UK English and "RU" for Russian.

P.S. `--keylayout 1` also doesn't appear to differentiate between UK and UK English which is annoying(

**Comment by Raymo111** [comment]
I'm not understanding. Keylayout is the keyboard layout. If you read the manpage, there are 3 options, 0 1 and 2. 0 is for the full keylayout string (i.e. `English (US)`). 1 is for the part before the parenthesis (i.e. `English` in the previous example), and 2 is for the part enclosed within the parentheses (i.e. `US` in the first example). Usually `--keylayout 2` will result in a 2-letter code, like in your screenshot above. I don't quite under your postscript either, since your screenshot clearly shows `English` as the result of `--keylayout 1`.

Whatever the case is, what's in the parenthesis and outside the parenthesis is decided by the name of your actual keyboard layout, not by i3lock-color (there isn't a table of all the keylayouts in this program). Perhaps you can consider changing the name of the keyboard layout in your OS?

**Comment by Rizhiy** [comment]
Sorry, I'm not sure how you are getting layout string. I'm using `setxkbmap` to manage my layouts, i.e. `setxkbmap -layout gb,ru -option 'grp:caps_toggle'`.
What I would like is to get the two-letter code similar to xkeyboard in polybar: https://github.com/polybar/polybar/wiki/Module:-xkeyboard

Here is the link to their code, just in case: https://github.com/polybar/polybar/blob/1dc8d2f30e248d2ca186d7dcf2972c5111dc3fa2/src/modules/xkeyboard.cpp

**Comment by Raymo111** [comment]
@Rizhiy Sorry for the month-long silence. i3lock-color gets the keyboard layout based on the method from [this gist](https://gist.github.com/bluetech/6061368), and gets the short keyboard string by parsing the long one for text within () brackets. Perhaps your keyboard layout string has no brackets in it? What do you get when using `--keylayout 0`?

**Comment by Raymo111** [comment]
Closing this for now, if you have followup comments I'll reopen.
