### ISSUE TITLE
[request] Draw shape under indicator and text

### ISSUE THREAD

**Issue by jeffmhubbard** [Raymo111/i3lock-color#209]
## This issue is a....

<pre>
[ ] Bug
[ x] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

Indicator and text are rendered directly over image or background color. (not a bug)

## Expected Behavior

It would be awesome if we had an option to draw a shape (circle, rectangle, rounded rectangle, etc) to put beneath the indictaor and\or text. The shape should be able to be configured (shape, radius, geometry, color, opacity).

In [betterlockscreen](https://github.com/pavanjadhaw/betterlockscreen) and my fork [multilockscreen](https://github.com/jeffmhubbard/multilockscreen), we use ImageMagick to draw a rectangle onto our background images. Usually this works, but user's with HIDPI displays continue to have problems with the positioning of the rectangle. Having this feature built in to `i3lock-color`, would allow us to use native DPI support and positioning. This feature would add a lot of possibilities to theming as well.

I can't contribute code, but I wanted to put the idea out there for anyone who can.

## Environment
Output of `i3lock --version`:
<pre>
i3lock version:
i3lock: version 2.13.c.2 © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2020 Raymond Li
</pre>

Where'd you get i3lock-color from?

<pre>
[x ] AUR package (which one?)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment]
I have some qualms about this, namely: the position of any element can already be configured, and some people have clock in bottom left and indicator in top right for example. If we allow drawing of only one shape, it wouldn't be enough, so we would have to allow for drawing an unlimited number of shapes, of a variety of types, with different fills, borders, text inside, etc. At this point i3lock-color would basically be an art program instead of a lockscreen, so I'm going have to say it's very unlikely that this feature will be implemented.

**Comment by jeffmhubbard** [comment]
That's a fair enough reason.
