### ISSUE TITLE
Screens flickering

### ISSUE THREAD

**Issue by niraami** [Raymo111/i3lock-color#24]
A while back after updating my system (not only i3lock), my screens started flickering when running i3lock.
I tested this on my two Arch machines, a notebook and a desktop, tried the AUR package, compiled from source, exact same result. I was wondering if my something is wrong with Cairo or some driver, but original _i3lock_ still runs fine and nothing else is acting the same way.

The machines are similiar software and driver-wise, but with completely different hardware.
What info do you need to help me solve this?

**Comment by niraami** [comment]
When you reply I'll add more stuff here: https://pastebin.com/kAMHRHF5
Or if you want, I can post it here.

**Comment by PandorasFox** [comment]
Hm, my laptop and desktop have Intel and AMD GPUs respectively, so I can't really test that easily.

This line in question:

`X11 Error received! sequence 0xd5, error_code = 4`

has me somewhat suspect, since it isn't pre-pended with `[i3lock-debug]`, which makes me pretty sure it's in a library outside my control. I'll poke around a bit and see where I differ from mainstream i3lock, and I'll see where this might be happening. I have a couple hunches.

**Comment by PandorasFox** [comment]
Alright, so I checked, and I honestly have no clue how this is happening. If you _really_ want to try, you could run i3lock under gdb in a tmux pane, then switch to another tty, attach that pane, and step through until you figure out what's giving the x11 error, I guess.

I can't see where that'd be coming from (though it's definitely a possibility that this is something I caused by doing something poorly)

**Comment by AeroX2** [comment]
Hello,
I have also been receiving this exact same error
> X11 Error received! sequence 0xd5, error_code = 4

but instead of the screen flickering, applications draw over i3lock (So for example XFCE's clock draws on top of i3lock)

No idea what the error is but I heavily suspect it has something to do with compton (The window compositor I use), when I killed compton and ran i3lock-color, it ran perfectly, nothing drew on top of i3lock and there was no X11 Error.

Some other things to note
- If I change compton to use the GLX backend instead of the XRender backend, i3lock-color works perfectly
- I tried a number of i3lock forks (lixxia, popoffka) and they don't seem to have this problem.

**Comment by niraami** [comment]
Goddamnit, I forgot that I had Compton even installed, it caused me a bunch of problems before!
Indeed seems like the same problem, killing Compton solved it, and other i3lock-s don't behave in this way. But my i3wm doesn't draw over it, I think... It's hard to see when the whole screen flickers white 3-4 times a second.

I'll try the GLX backend later, though I doubt I'll keep using it, as I heard I affects performance in video playback and games a lot.

**Comment by PandorasFox** [comment]
I'm using compton myself without problems, so this is interesting (and probably related to #27)

**Comment by PandorasFox** [comment]
I still haven't actually been able to reproduce this with a number of different compton configs/backends, but I've been able to reproduce the issue with xfce's compositor stuff, so I'll (hopefully) have a fix out for that issue relatively soon.

Hopefully that will also fix this issue. If not, I'll keep on working on that, but for now I'm assuming that these have the same root cause.

**Comment by PandorasFox** [comment]
I'm likely going to end up adding a `--composite` option for this at some point.

Can you go checkout both https://github.com/google/xsecurelock and i3lock 2.9 and see if they have similar issues?

There appear to be a couple issues related to compositors and screen lockers, but I can only reproduce them across the board, and not _only_ with i3lock-color, so I'm not sure there's much I can do.

**Comment by niraami** [comment]
You are probably onto something, both xsecurelock, and i3lock-2.9 does the same thing now. Although not i3lock-2.8-1 which the arch repo is supplying.
Are you using the latest i3lock-2.9 in your release?

**Comment by PandorasFox** [comment]
I am indeed. 

[This commit](https://github.com/i3/i3lock/commit/80d4452ec680bcb0e57418f69d44d88ded82047c) was included in the latest i3lock release.

There's some talk about it at https://github.com/i3/i3lock/issues/128. You may want to poke over there about it.

I'll be closing this as an upstream issue for now, since it's not unique to i3lock-color.

**Comment by PandorasFox** [comment]
> I'm likely going to end up adding a --composite option for this at some point.

With d9f2e04bab3c5f2bed674edd085355da255f892b, I added a `--no-composite` argument for disabling dealing with compositors. Using that should help some.
