### ISSUE TITLE
Slideshow Image Loading Improvements

### ISSUE THREAD

**Issue by Qwerty-Space** [Raymo111/i3lock-color#241]
## This issue is a....

- [ ] Bug
- [x] Other kind of issue (Please describe in detail)

## Current Behavior

Multiple images are loaded at runtime when using the slideshow feature

## Desired Behavior

Load additional images after runtime, as needed.  Perhaps implementing a --slideshow-cache argument for pre-loading a few ahead.  Must bear in mind discarding used images if the cache is the same size as the entire folder.

**Comment by JezerM** [comment]
Ok, there's a solution to this, currently implemented in my [PR](https://github.com/JezerM/i3lock-color/blob/9f6e69f899508b99af7aea659ac63a66179f6eae/api.c#L301-L312), #235.
```c
image_path = NULL;
update_arguments(argc, argv, longopts, optstring, true);

if (image_path != NULL) {
    if (!is_directory(image_path)) {
        pthread_mutex_lock(&redraw_mutex);
        img = load_image(image_path, image_raw_format);
        pthread_mutex_unlock(&redraw_mutex);
    }
    free(image_path);
}
free(image_raw_format);
```

Here, when you send a `--image path_to_some_image` message to the API, this will load the image as it is right now. If you send it again, the image will be loaded as it is right now, not as it was before. So, replacing the current array with something like this should solve this "static" problem.

Also, doing this at short intervals is dangerous, laggy and could crash; that's why I didn't go with this idea before, but an advice should be enough.
