### ISSUE TITLE
lock.sh is very slow

### ISSUE THREAD

**Issue by mspronesti** [Raymo111/i3lock-color#243]
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

the provided script [lock.sh](https://github.com/Raymo111/i3lock-color/blob/master/examples/lock.sh) takes 3 to 4 seconds to lock the screen while running `i3lock` locks the screen in a heartbeat.

## Expected Behavior

The script to take less than 1 s to lock the screen

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.13.c.4-17-g4ff79c0 (2021-08-09) © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2021 Raymond Li
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[x] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by JezerM** [comment]
That's due to blurring, which is slow and has been stated some times before: #129, #239. For the moment, you can delete [this line here](https://github.com/Raymo111/i3lock-color/blob/995f58dc7323d53095f1687ae157bfade1d00542/examples/lock.sh#L31) and try to use either a **simple image**, or a **transparent background** with `--color 00000000` and a compositor like **compton** or **picom**.
