### ISSUE TITLE
Trace after unlocking

### ISSUE THREAD

**Issue by ghost** [Raymo111/i3lock-color#27]
After unlocking, the program trace remains on the screen. I use xfwm4 with enabled compositing and Intel HD video card. The original i3lock don't have such issue
Video:
https://youtu.be/9K-03gn7nkA

**Comment by PandorasFox** [comment]
What driver version and what version of xfwm do you have?

**Comment by ghost** [comment]
xfwm4  4.12.4-1
xf86-video-intel  1:2.99.917+772+gc72bb27a-1

**Comment by ghost** [comment]
The issue appears only when compositing enabled and with xfce4 built-in compositor

**Comment by PandorasFox** [comment]
Seems like I have a commit _somewhere_ that isn't playing well with some compositors. I'll start investigating.

**Comment by PandorasFox** [comment]
Alright, I'm able to reproduce this. I'm fairly certain that this is a compositor issue.

**Comment by PandorasFox** [comment]
So, somewhat curiously - I have the same problem that you do, but I also get that problem when I'm using i3lock upstream. I'm fairly certain that https://github.com/i3/i3lock/commit/80d4452ec680bcb0e57418f69d44d88ded82047c is the culprit, so I'll be digging a bit into it and trying to figure out why.

**Comment by PandorasFox** [comment]
So google's [xsecurelock](https://github.com/google/xsecurelock) also has problems with the compositor window getting garbled after the unlock.

As far as I can tell, this is an issue with the compositor not properly re-compositing after the screen locker releases the overlay window, or something.

The latest version of compton works fine for me, whereas the xfwm compositor sorta breaks _a lot_, with both i3lock 2.9 and xsecurelock.

Can you go check out both/either of those and see if this issue is only with i3lock-color, or with multiple of them? If it happens to more than one, then it's mostly likely either upstream i3lock's problem, or a problem with xfwm's compositor.

Thanks!

edit: also, if you check #24, I added a `--no-composite` argument in d9f2e04bab3c5f2bed674edd085355da255f892b. That may also solve your problem.

**Comment by ghost** [comment]
xsecurelock - has issue.
I just found that ti3lock 2.9 has issue while i3lock 2.8-1 not.
i3lock-color with --no-composite argument solve problem.
