### ISSUE TITLE
`./configure` fails to find libev in `/usr/local/lib`

### ISSUE THREAD

**Issue by anoduck** [Raymo111/i3lock-color#282]
## This issue is a....

<pre>
[ ] Bug
[X] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

Regardless of libev being installed and PREFIX appropriately set to `/usr/local/`, the configuration script still cannot locate libev. So, I need to know:

1. What version of libev is required?
2. What are the names of the libev files needed. (sometimes they differ)

I currently have:
```bash
/usr/local/lib/libev.a
/usr/local/lib/libev.la
/usr/local/lib/libev.so.3.1
```
3. Does libev.so.3.1 need to be libev.so.0? (Yes I know the version number is designated after the extension).

## Expected Behavior

Correct configuration and compilation.

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 2.14.1
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[x] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by sh1r4s3** [comment]
@anoduck JFYI `configure` gets generated from `configure.ac`. You can try to regenerate `configure` from scratch with:
```sh
$ autoconf -fisv
```

In the `configure.ac` i3lock-color doesn't check for any particular version of `libev.so`:
```config
# libev does not ship with a pkg-config file :(.
AC_SEARCH_LIBS([ev_run], [ev], , [AC_MSG_FAILURE([cannot find the required ev_run() function despite trying to link with -lev])])
```

Basically, the resulting `configure` will try to link against `libev.so`. Usually, Linux distros do symlink to the actual version of the library. But it is seems that since you have libev in `/usr/local/` you've built it yourself. However, even if you build libev from the sources during `make install` it should create a `libev.so` symlink, check that you have one.

**Comment by anoduck** [comment]
@sh1r4s3 Brutal honesty, I am not thinking as clearly as I should be. Lack of sleep, and stress, are a deadly combination. 

1. My operating system is OpenBSD 7.3 CURRENT-SNAPSHOT

2. My apologies, it would probably help if I included the actual output error, which I normally do. 

```bash
configure: error: in `/home/user/Sandbox/i3lock-color/x86_64-unknown-openbsd7.3':
configure: error: cannot find the required ev_run() function despite trying to link with -lev
See `config.log' for more details
```

3. I have attached the `config.log` below. You will probably make more out of it than I can. 

[config.log](https://github.com/Raymo111/i3lock-color/files/12115405/config.log)

I3 version = 4.22 
C compiler is clang, but gcc is available as well.
Autoconf is 2.69, 2.71

**Comment by sh1r4s3** [comment]
@anoduck that's ok :) so from the `config.log` you've provided it is seems it can't find `libev.so` library to link against:
```
configure:6099: cc -o conftest    conftest.c -lev  -lm  >&5
ld: error: unable to find library -lev
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```

I've downloaded the OpenBSD 7.3 [libev-4.33.tgz](https://cdn.openbsd.org/pub/OpenBSD/7.3/packages/amd64/libev-4.33.tgz) and it's doesn't have the `libev.so` symlink:
```
./man
./man/man3
./man/man3/ev.3
./include
./include/ev.h
./include/ev++.h
./lib
./lib/libev.la
./lib/libev.a
./lib/libev.so.3.1
./+DESC
./+CONTENTS
```

I'm not an OpenBSD expert so I don't know if it is OK if the distro doesn't provide a symlink. IMO this is a flaw of the pkg because I believe that every client of libev wouldn't work with this pkg.

**Comment by sh1r4s3** [comment]
You can try to ask to fix this in <ports@openbsd.org>

**Comment by anoduck** [comment]
@sh1r4s3 AH, that explains it. Alright, I will shoot an email over to ports@openbsd.org, and see if I can get in touch with @naddy concerning it.
