### ISSUE TITLE
Some bugs / questions

### ISSUE THREAD

**Issue by felixsanz** [Raymo111/i3lock-color#29]
Bug: If you set a big timesize or datesize, the text appears "cut", even if there is enough screen space.

Question: Having a bigger font, how do you center it across the indicator? It's almost impossible because of the combinations and the bug that i specified above :/

**Comment by felixsanz** [comment]
I forgot another thing: It is possible to separate the date from the time? When the font is bigger, the space is smaller, and that becomes a problem at some point

**Comment by PandorasFox** [comment]
The font being cut off is something I know about, since it's inside the indicator canvas and doesn't get rendered outside that. It's part of why there's no text positioning for that - it's part of the indicator, and not worth separating, since it'll make maintenance a lot more complex.

With a bigger font, it should still be centered, albeit cut off.

The date and time are already separate - you can set their formats, positions, sizes, and fonts separately. The date position defaults to time_x:time_y+20 (maybe 30; I forget the exact value off the top of my head).

**Comment by PandorasFox** [comment]
Going to close this for now, since the 'cutting' behavior is intended currently.

**Comment by schaden-freude** [comment]
Hey! Are there any plans to change the 'cutting' behaviour as of now?

**Comment by PandorasFox** [comment]
I'll look into having the different Cairo canvasses scale with the font size, but I probably won't fix this until after my term projects are done lol
