### ISSUE TITLE
Feature request: Keyboard Layout indicator

### ISSUE THREAD

**Issue by SuperPrower** [Raymo111/i3lock-color#39]
Title says it. I have 2 keyboard layouts, and I can't remember which one I had, so it usually takes 2 to 3 attempts to unlock my laptop.

Author of original i3 refuses to add such feature. There is [fork](https://github.com/cac03/i3lock) that implements such feature, but it lacks i3lock-color customization.

**Comment by PandorasFox** [comment]
I'll definitely give this the same treatment as indicator positioning and stuff. Might take me a while since I've got like 3 exams in the next week, though.

**Comment by PandorasFox** [comment]
My motherboard just died, so I'm pretty much upgrading my dev rig to Ryzen now. My progress will be halted until then, so my estimated time on this is probably just end of october for now :&

**Comment by SuperPrower** [comment]
No haste, it's not something that makes program unusable or something. Good luck with your upgrade.

**Comment by PandorasFox** [comment]
This'll be a bit tricky, since I'm trying to find a _good_ way to do it without bringing in any extra libraries - I'd like to stay pretty close to upstream in most regards; the way most other projects do it is sorta hacky.

(though frankly, apparently it's _really_ hard to get the active keyboard layout in C. God knows why.)

If it's exposed through an environment variable at all that'd be ideal, but I suspect that's not the case.

**Comment by SuperPrower** [comment]
What about Xkb library? I have working solution with this library, and I could possibly create pull request with this feature complete and working, if it's ok - i3lock doesn't work with Wayland anyway, so why not to use Xorg library?

**Comment by PandorasFox** [comment]
Actually, the last time I experimented with Wayland, i3lock actually worked when you recompiled and ran it. Not sure about it now with the compositor stuff, but it did work.

I'll keep looking at this - we should already be using the xcb-xkb libs, so that's fine. Most of the other solutions I've seen require x11 libs, which is what I'm trying to avoid, since it'll require more libs to be linked in the Makefile.

**Comment by SuperPrower** [comment]
Ok, I'll try to create pull request sometime soon.

**Comment by PandorasFox** [comment]
heyo!

I had the time to sit down finally. [Here](https://github.com/chrjguill/i3lock-color/tree/keylayout)'s what I have so far.

(I refactored a decent amount of code to make this more maintainable, so it should be a bit easier to do color work in the future).

Currently, the keylayout only shows if the clock / text is showing, and is only checked once (so if your keylayout changes while i3lock is running, stuff will break a bit - not too hard to fix, but I don't think that that's possible?)

I can probably rework it some so that the keylayout always shows, though.

**Comment by PandorasFox** [comment]
This has been merged into master, so in closing this now.

**Comment by webknjaz** [comment]
Bug: https://github.com/PandorasFox/i3lock-color/issues/115
