### ISSUE TITLE
adding text under the ring

### ISSUE THREAD

**Issue by 2Belette** [Raymo111/i3lock-color#42]
i3lock permits to put some text like 'Type password to unlock" below the ring but I don't find the option here?

Thanks :)

**Comment by PandorasFox** [comment]
Upstream i3lock doesn't, and neither does my fork. 

i3lock-fancy does stuff by rendering the text on to the image that it uses as the i3lock background. While I'd like to add some text support, I'd need to do positioning, fonts, etc. which I'd rather keep to a minimum, and probably am not going to ever handle here due to a lack of time to add featured for now.

**Comment by 2Belette** [comment]
ok thanks for your reply, and yes I meant i3lock-fancy when I mentioned i3lock
