### ISSUE TITLE
Support to set font for verification text

### ISSUE THREAD

**Issue by lokesh-krishna** [Raymo111/i3lock-color#60]
I couldn't find any option that lets one set the font for the verification text presently. Could you please consider adding one so that it can be consistent with the fonts for date and time?

**Comment by PandorasFox** [comment]
I'm currently waiting for [this pull request](https://github.com/i3/i3lock/pull/168) to get merged upstream before I do any working with font stuff, pretty much.

It's planned, since once that gets merged I can rewrite a decent amount of the font/text handling to be more efficient and to be easier to work with.

**Comment by PandorasFox** [comment]
This is included as of commit 6b943766dae08295e8ecdeb81d126e9f06f39194 in `dev`, please give it a look when you can - it's part of a pretty big refactor, so there might be a few bugs in it right now that I didn't catch.

**Comment by PandorasFox** [comment]
This is in master now and should (hopefully) be fine... at least, it works on all my machines/with my tests :>
