### ISSUE TITLE
Indicator position bug

### ISSUE THREAD

**Issue by icekom** [Raymo111/i3lock-color#69]
`i3lock --indicator` looks like this:
![screenshot from 2018-01-25 20-00-28](https://user-images.githubusercontent.com/23084830/35401396-6cf06556-020a-11e8-9de7-e03bbb85f515.png)

`i3lock --indicator --indpos="w:h"`:
![screenshot from 2018-01-25 20-00-16](https://user-images.githubusercontent.com/23084830/35401430-893d15a6-020a-11e8-81c9-2235bd2e318d.png)

`i3lock --indicator --indpos="0:0"`:
![screenshot from 2018-01-25 20-04-05](https://user-images.githubusercontent.com/23084830/35401603-0a36488a-020b-11e8-8179-e6ec5705eede.png)

My resolution is 1920x1080 and i don't have any problems with regular version of i3lock (correctly centered).

**Comment by PandorasFox** [comment]
To double check, you're building from source, from the latest revision, correct?

I did a pretty big refactor and was pretty sure there would be some issues with positioning now, but didn't notice any. I'll give this a look this evening if it's the latest version (and hopefully have a patch out this weekend)

**Comment by icekom** [comment]
Yes, built from source recently.

**Comment by PandorasFox** [comment]
Weird. I'm running two monitors (2560x1440 + 1920x1080, with the latter aligned to the bottom) and this is what I'm getting:

`i3lock --indicator`
![2018-01-25_18 42 19-9594ad](https://user-images.githubusercontent.com/3235827/35418372-df918370-01ff-11e8-8bf5-737b708dc10e.png)

`i3lock --indicator --indpos="0:0"`
![2018-01-25_18 41 54-6119df](https://user-images.githubusercontent.com/3235827/35418405-04dcc392-0200-11e8-8434-8406d07d6cfd.png)

`i3lock --indicator --indpos="w:h"`
![2018-01-25_18 41 38-2bf734](https://user-images.githubusercontent.com/3235827/35418406-04ed3fa6-0200-11e8-81ee-4d6d11be23cc.png)

`i3lock --indicator --indpos="2560:1440"`
![2018-01-25_18 41 17-2e425a](https://user-images.githubusercontent.com/3235827/35418407-04ffca2c-0200-11e8-9aaf-2eaa75892de1.png)


Looks like it's working properly for me, so I dunno what's wrong. Could it be that you have some display scaling stuff / a weird DPI that's causing it to attempt to scale where it's drawing? (or it could be that my refactor dropped some of the scaling code accidentally)

**Comment by PandorasFox** [comment]
can you re-run i3lock with `--debug` and post the contents? The scaling factor for my screen is 1.0, so if yours is different that might be why.

**Comment by icekom** [comment]
> [i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0) @ [1516924896]
> [i3lock-debug] scaling_factor is 1, physical diameter is 178 px

Scaling factor is 1.

I just tried running it with gnome and it was properly centered. It's only a problem on i3.
On gnome `i3lock --debug` says that physical diameter is 186px, but scaling factor is still 1.

**Comment by PandorasFox** [comment]
huh. I'll have to give that a look.

The only reason why they'd differ would be if the ring radius or width were changed, but I don't see why your DE would influence that.

**Comment by PandorasFox** [comment]
I guess I'm going to have to poke at popping up a VM this weekend to test this. I can't repro this on any of my machines.

What distro/setup do you have? I'm guessing you have some distro / distro variant that had gnome by default, but you're using i3 now.

**Comment by icekom** [comment]
Ubuntu 17.10. I'm using i3-gaps.

**Comment by icekom** [comment]
Here's a report of my setup: https://pastebin.com/DPbWFQiY

And my i3 config: https://pastebin.com/aR3qzptC

**Comment by PandorasFox** [comment]
Thanks. I'll give a VM a stab later tonight and see if I can repro it.

I think this wins the "most interesting bug" award so far :D

**Comment by PandorasFox** [comment]
Oh yeah, one last thing - can you also log into both gnome and then i3-gaps, and then run `xrandr` in both, and post the outputs?

I have some guesses about what's going on; I _think_ it might just be that the xinerama/xrandr calls to get the display info get back incorrect data somehow.

**Comment by icekom** [comment]
`xrandr` output is _exactly_ the same in both i3 and gnome: https://pastebin.com/n4v6mz97

**Comment by PandorasFox** [comment]
Alright, thanks. That should be everything I need to set up a VM to test this on.

**Comment by PandorasFox** [comment]
Yeah, so I got a VM set up and... it just works as expected.

![image](https://user-images.githubusercontent.com/3235827/35466179-88de695a-02cf-11e8-8756-aa043243d13a.png)

I have no idea what to say at this point (other than that getting all the packages needed to build on ubuntu 17.10 was more annoying than I'd guessed). I just can't repro this, so I have no idea why it's happening :/

My best guess is that somehow, the [xrandr screen info](https://github.com/PandorasFox/i3lock-color/blob/master/unlock_indicator.c#L850) is somehow just being... wrong. Which doesn't make sense since the image is covering the entire screen. (I was assuming your xrandr output would look a bit weird in i3, but... nope.)

Once I get this to repro it should be pretty easy to fix (although pretty hard to understand, I imagine).

**Comment by icekom** [comment]
I can try to make a virtualbox disk image with that bug reproduced based on my system. I'll do it in a few days, busy right now.

**Comment by PandorasFox** [comment]
No big rush. I'll be busy for most of the next week, so I'll be able to give it a a stab next week.

**Comment by Eyenseo** [comment]
@PandorasFox This issue arose as you deleted `ch` and `cw` in 6b943766dae ([L.639](https://github.com/PandorasFox/i3lock-color/commit/6b943766dae08295e8ecdeb81d126e9f06f39194#diff-efe870ebf4bb57bf7e8e1316d4526cdaL639)) thus e.g.`te_ind_y_expr` will be NULL and we stumble in [L.861](https://github.com/PandorasFox/i3lock-color/blob/master/unlock_indicator.c#L861) where apparently `y ` equals to the height of the screen.
You might also want to adjust the manpage as it still lists `cw` and `ch` - if you really intended to delete them.

**Comment by PandorasFox** [comment]
> if you really intended to delete them.

I did, since they have no meaning now. Before they were statically set to the height/width of the clock canvas - 200/400, I think (maybe 200/600, it's been a while).

Now everything is just drawn straight onto the main canvas since it's faster/relies on less hacky positioning. There's no cw/ch _to_ use, so they're meaningless - the only point of them before was to help with left/right/centering the canvas on stuff, but that's been surpassed by `--time-align` and stuff.

> This issue arose as you deleted ch and cw in 6b94376

Surprisingly, a friend of mine mentioned that they had this issue last fall, but they just figured out the offset and worked around it. It seems to be environment/library related somehow (and this isn't properly taking something into account).

> where apparently y equals to the height of the screen.

But that _should_ mean that `y` is aligned along the bottom edge of the screen, but instead, the center isn't bottom aligned - it's slightly up and to the left of where it should be (the bottom right corner).

> You might also want to adjust the manpage as it still lists cw and ch - if you really intended to delete them.

I just did that in the dev branch, thanks. I _really_ need to redo those docs before any other big changes.

edit: also a bit of a note, I can't reproduce this currently. If it was related to cw/ch, we'd see this when those variables get used, but when they're unused, the positioning can't impact it.

@icecom64 - can you also go retry this with `--indpos=1920:1080` and compare it to `w:h`? I'm curious as to whether it's an issue the expression parsing, since it may be that I goobered something up with that.

**Comment by Eyenseo** [comment]
@PandorasFox So I tried removing the `ch` and `cw` (just using `w/2` and `h/2`) - it did center my clock but it disappeared once I started typing. The indicator on the other hand did not show up (using the same expressions). Then I tried fixed cords for the indicator, which made the indicator show up. While doing that I noticed that the clock will be moved onto the indicator when typing. Another thing I noticed is that the indicator and clock only show up on one display - not on both as previously.

The thing with the fixed cords is the following; If I set the center of my screen the clock will be centered correctly, when I type the clock disappears and the indicator is no where to be seen. When I give "lower" cords the indicator appears "somewhere" I guess this has to do with the scaling (debug: `scaling_factor is 2, physical diameter is 57 px`) but it is definitely not multiplying them - I do not know what is calculated there.

**Comment by PandorasFox** [comment]
What laptop/display do you have? I haven't ever actually figured out what kind of hardware gets you an actual scaling factor.

Where are you removing ch and cw from? (Assuming you mean your command-line arguments, then yeah, that's what should happen).

Can you post exactly what arguments and version info (`i3lock --version`) you have, and list what your setup is (what distro, what display(s), what window manager, etc. 

Both my laptop and desktop run arch linux, but I've been unable to reproduce this myself on a couple different ubuntu VMs / a fedora VM, so I'm assuming that this is a hardware specific issue that I just simply don't/can't encounter.

I might later put up a debug build in a `debug` branch that'll print out extra positioning info, which should help a decent amount.

**Comment by icekom** [comment]
@PandorasFox `--indpos="1920:1080"` looks the same as `--indpos="w:h"`. I couldn't reproduce it on a VM.

**Comment by Eyenseo** [comment]
@PandorasFox `cw` and `ch`were removed from the cmd ;) 
`i3lock: version 2.10.1-2-c (2018-01-23, branch "tags/2.10.1-2-c") © 2010 Michael Stapelberg` (commit f3a12c6) on Archlinux, i3-wm,  15" 3200x1800 and external 27" 2560x1440 but scaled to 3200x1800.

**Comment by PandorasFox** [comment]
@icecom64 That makes things even weirder. I'll add some debug stuff into the dev branch for you both that should print some stuff to help me out.

@Eyenseo how're you doing the scaling (I'm guessing through xrandr)/what specific modes/scaling? I should be able to emulate some X screens into a similar state and see what I can repro

**Comment by PandorasFox** [comment]
Can you give the changes in @71 or @72 a shot? I'm looking it over and nothing strikes out at me as potentially fixing this, but I'm curious.

It seems the issue you were getting was that the base xcb canvas with the image was covering the screen properly, but then everything else was getting scaled somewhat (even though scaling_factor was 1.0), which didn't really make sense.

(Even if it doesn't, it has some extra debug output that may be handy)

**Comment by icekom** [comment]
#72 fixes this bug. But i get [memory leak error](https://gist.github.com/icecom64/af14e5e1fc725d1dbeaaa32f2998eaf2)

**Comment by PandorasFox** [comment]
What command are you invoking i3lock with? I didn't see any memory leaks in my testing, but ~~u~~ I didn't test variable fonts too much.

**Comment by PandorasFox** [comment]
Can you check https://github.com/PandorasFox/i3lock-color/commit/85b6b5b11704f57cb75a432ebb76a4ed336576f6 ?

I did some checking and used some debug versions of fontconfig and libexpat - I got exactly two leaks reported, both related to some stuff in the fcinit() call. Calling fcfini() frees those and should make there be no leaks (aside from stuff used explicitly for drawing stuff, i.e. the font faces themselves).

If you still have memory leaks then, what you may need to do to get better debug info is:

* clone and build a local version of fontconfig, with ASAN enabled in it (i.e. clone, then do `./configure CFLAGS="-g -fsanitize=address -fno-omit-frame-pointer"`)
* invoke i3lock with `ASAN_OPTIONS=log_path=./asan_log LD_PRELOAD=/usr/lib/libasan.so:/usr/local/lib/libfontconfig.so ./i3lock [...]`

Having ASAN log to files keeps its output from being intertwined with itself across children; the files should all be identical, but more readable this way.

I didn't see any leaks at all by default, until I compiled those libs myself, so I'm not sure what's being reported for you, since that looks like the false positive I fixed a while ago.

**Comment by PandorasFox** [comment]
Merging the fixes in #72 somehow autoclosed this issue; dunno why github did that, but I can't repro this so I'm not going to close it without some confirmation

**Comment by icekom** [comment]
85b6b5b fixes memory leak, everything works as it should.

**Comment by PandorasFox** [comment]
ayy, awesome.
