### ISSUE TITLE
Feature Request: Separate indicator color options for each indicator

### ISSUE THREAD

**Issue by owenthewizard** [Raymo111/i3lock-color#75]
F.e., indicator on monitor 0 could have `--insidecolor=000000ff` while the indicator on monitor 1 could have `--insidecolor=ffffffff`. I think this would be a worthwhile addition because it could be used by other applications to set the indicator colors based on e.g. the background lightness, which I'd like to do within my own i3lock-next.

**Comment by PandorasFox** [comment]
That'd be pretty nice, but it'd complicate things a bit (i.e. specifying different values for 3 different displays would become very gross, very quickly).

If I move to something like that, it'd probably be worth it to rewrite from a bunch of command-line arguments to using a config file(s), which I've been meaning to do for a while. Arg parsing/options has been needing to be redone for a long while now, so while it's fine-ish to keep hacking in new arguments, something like this would take quite a bit of work.

**Comment by PandorasFox** [comment]
(this is definitely something I've been thinking of in the past, since it's a pretty interesting question of managing configs... really, the stuff for handling this on the drawing side exists now thanks to #72, so it just needs a big rewrite with configs)

The main problem is that with a config rewrite, I'd like to move to config files over the CLI, but that makes it harder for lock scripts and stuff to manage the appearance. Positional / repeated args to modify stuff might be possible, but it'd get pretty hacky.

One potential idea would be to let config files map a color or position to an environment variable, or something, so that then lock scripts can just specify their local config file and set env vars. (I'm a bit wary of just grabbing stuff out of the env for this, though)

Any feedback on what you think would be good ways to interface this would be good, since I'm not entirely sure how to go about this (it'll probably be a while before I have time to get around to this)

**Comment by meskarune** [comment]
>I'd like to move to config files over the CLI, but that makes it harder for lock scripts and stuff to manage the appearance.

Honestly a lock script could just set a config as it's default. Like how in conky you can do "conky -c \<path to file.rc\>" so I think having a text config would be useful.

**Comment by PandorasFox** [comment]
> Honestly a lock script could just set a config as it's default. 

I mean, it gets a bit weird for the lock script to have to `sed` that config each time before running if it replaces a color or something (unless it just quickly dumps a config file for i3lock to read or something). I feel like there should be a better solution than that

**Comment by meskarune** [comment]
Right, you could have i3lock-color use a default location for a config, and have that over ridden with the cli options and allow for custom config files. So script writers can write a config that goes with their script and do "i3lock-color -c scriptconfig.conf" inside their script. i3lock-color would fallback to the default config for things that aren't defined. This could even allow people to use one config for manual locking and one config for locking on suspend. People could do cool things like change the background depending on the time of day, using light background for the lock screen during daylight hours and dark backgrounds during the night. idk if this makes sense.

**Comment by PandorasFox** [comment]
I'm gonna be playing around and writing something from the ground up to figure out how to best do this in C (I might actually end up just working on making that project a pretty solid fork, if it ends up alright/being similar enough). I just did a bit of a rewrite to clean up the arg parsing's gigantic switch statement, but I don't think that there should be much done beyond that to what's there right now.

**Comment by PandorasFox** [comment]
Going to close this as this won't be implemented in i3lock, but it'll be something handled in the eventual successor (if I ever get that off the ground this fall)
