### ISSUE TITLE
Required packages for Ubuntu 16.04

### ISSUE THREAD

**Issue by dragon788** [Raymo111/i3lock-color#76]
Thanks to [this post](https://techmythoughts.blogspot.com/2018/01/installing-i3lock-color-on-ubuntu.html) I got most of the list, but I had to flail around for a while to find the last couple even though I'd previously installed them on other systems. The last one or two required a PPA and I typically like to keep the number of PPAs I have installed to a minimum, but this one I think has a few good packages for 

I was playing around with getting it to compile in a Docker container, and while I don't think I've narrowed down the list to only the bare minimum yet, installing ALL these packages at least allowed me to compile, and then installing them on my host let me `sudo make install` i3lock-color as `i3lock`.

```
FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y \
      build-essential \
      git \
      software-properties-common && \
    add-apt-repository -y ppa:aguignard/ppa && \
    apt-get update && \
    apt-get install -y \
      autoconf \
      automake \
      checkinstall \
      libev-dev \
      libxcb-composite0 \
      libxcb-composite0-dev \
      libxcb-xinerama0 \
      libxcb-randr0 \
      libxcb-xinerama0-dev \
      libxcb-xkb-dev \
      libxcb-image0-dev \
      libxcb-util-dev \
      libxkbcommon-x11-dev \
      libjpeg-turbo8-dev \
      libpam0g-dev \
      pkg-config \
      xcb-proto \
      libxcb-xrm-dev \
      libxcb-randr0-dev \
      libxkbcommon-dev \
      libcairo2-dev \
      libxcb1-dev \
      libxcb-dpms0-dev \
      libxcb-image0-dev \
      libxcb-util0-dev \
      libev-dev \
      libxcb-xinerama0-dev \
      libxcb-xkb-dev \
    && rm -rf /var/lib/apt/lists/*

CMD autoreconf -i && ./configure && make
```

**Comment by dragon788** [comment]
This could also be the list to update the `.travis.yml` for compiling on 16.04.

**Comment by crablab** [comment]
This also works for Ubuntu 17.10 minus `clang-format-3.5`

It's a shame there isn't a PPA for this - I'm happy to create one but I'm not sure whether @PandorasFox would be happy with that or whether they'd prefer to create it themselves.

**Comment by PandorasFox** [comment]
Yeah, I remember building in a 17.04 vm a while ago - I think everything but clang-format-3.5 was in the main repos.

I need to update the issue template and stuff when I do that as well, since I'd noticed that when there were easy instructions for building, there was a pretty high incidence of issues reported that'd already been fixed (i.e. people don't ever really update after they build and install once, which is something people should avoid with a screen locker)

Ideally I'd provide a PPA or .deb or something, but I haven't had the time to look into that. (I do have a ubtunu 16.04 VPS, so I could theoretically get that set up, I guess)

**Comment by PandorasFox** [comment]
(clang-format isn't required at all for building; it's just that it's supposed to be run before committing... However, I'm pretty lax on that, and not beholden to a specific version in any case. Upstream i3lock picked 3.5, but that's not a hard requirement and I'll probably change it to be less specific)

**Comment by dragon788** [comment]
Good to know, I'll pull it out of my comment since it's not required and I believe it may come in as a suggested package from build-essential or one of the other bits.

**Comment by dragon788** [comment]
If you just want to provide precompiled debs you can check out https://packagecloud.io or I believe https://bintray.io also has a free option for FOSS projects. Setting up a PPA seems to be a bit of work and it seems like most folks who do so end up not taking the extra step of making the updates automatic so they only end up with a single version of a package and never attempt newer builds. I think the big hiccup with the PPAs is that usually you have to push your source code into Launchpad via Bazaar `bzr` unless they changed that since the last time I looked (a long while ago).

**Comment by PandorasFox** [comment]
(I find it a bit amusing there's like, blog posts and stuff about using this fork. Definitely seems to have grown beyond what I ever expected it to...)

and yeah, I don't really imagine that Launchpad will be fun to work with, but I imagine I can probably just get some gross script set up that'll automate it all. The build process shouldn't ever change, and I trust myself enough to probably not break the build and then shoot myself in the foot, so it should be relatively painless for me to update a ppa fairly regularly.

Bintray does look pretty neat, though. Getting set up with that would be pretty nice, since if I can provide a .deb _and_ a .rpm that should be good enough for like, what, 90% of linux users? It's probably about time I uh, actually do something on that front, I guess.

**Comment by dragon788** [comment]
If you want to be really cross platform there's also 'fpm' that helps build a ton of package types from various input sources.

**Comment by PandorasFox** [comment]
Ooh, that'd be nice.

I think my one main concern is that I know a few distros had problems with the i3lock Pam file not being installed correctly, so I guess I'd need an afternoon or two to spin up some VMs and try it out on all of them.

It's definitely something I'm interested in doing soon™, but I'll be a but busy this semester, unfortunately.

**Comment by NeuroWinter** [comment]
Even after installing all the packages I cannot seem to build this in 18.04 I get this error when running 


`sudo autoreconf -i && ./configure && make`

```
configure: error: Package requirements (xcb xcb-xkb xcb-xinerama xcb-randr xcb-composite) were not met:

No package 'xcb-randr' found
```

**Comment by Pysint** [comment]
@NeuroWinter I stumbled across the same issue today, and managed to resolve it by installing the missing packages. Libxcb packages are not available from the standard Ubuntu repo, so require you to add a PPA:

`sudo add-apt-repository ppa:aguignard/ppa`
`sudo apt update`
`sudo apt install libxcb-keysyms1-dev libxcb-randr0-dev`

After installing libxcb* packages, it also turned out it requires libjpeg which can be installed from the Ubuntu repos:

`sudo apt install libjpeg-turbo8-dev`

After this I was able to build/install this beautiful tool as such:

`sudo autoreconf -i && ./configure && make`
`cd ~/Downloads/i3lock-color/x86_64-pc-linux-gnu`
`make -j`
`sudo make install`

Hope this helps. Tested on Ubuntu 18.04 latest. General note for those getting stuck from the start: Ubuntu requires the autoconf package to be installed manually with; `sudo apt install autoconf`.

**Comment by NeuroWinter** [comment]
Thank you so much @Pysint, that solved my issue, it also turned out I needed cairo:

`sudo apt-get install libcairo2-dev libjpeg-dev libgif-dev`

After that everything worked wonderfully.

**Comment by aiguofer** [comment]
Not sure if this works on 16.04, but it does for 18.04:

 https://github.com/codejamninja/i3lock-color-ubuntu

**Comment by Raymo111** [comment]
Fixed in Readme.
