### ISSUE TITLE
Error while loading shared libraries libasan.so

### ISSUE THREAD

**Issue by imamdigmi** [Raymo111/i3lock-color#79]
Hi! thanks for great i3lock improvement, I tried to install in Arch via [AUR](https://aur.archlinux.org/packages/i3lock-color) in stable version and installation is successfull but when I trying to run `i3lock` I got error something like this
```
i3lock: error while loading shared libraries: libasan.so.3: cannot open shared object file: No such file or directory
```
I think the way I installing it is right but I dont know why `libasan.so` suddenly dissolve, but when I try to install it via [Git/Unstable version](https://aur.archlinux.org/packages/i3lock-color-git) `i3lock` is works well but I got a blank screen (white), is this right? thanks!

**Comment by PandorasFox** [comment]
The stable version doesn't properly build (it's building a debug version). The git version properly builds so that you don't have a debug version.

I don't know why you're having the ASAN issue - you might be using an older version of gcc/clang , or possibly need to add -lasan to your compile args. In either case, it's not building a release version, which isn't supposed to happen

**Comment by dannycolin** [comment]
Just in case someone else stumble upon the same problem : 

You can use `./configure --enable-sanitizers` with GCC :).
