### ISSUE TITLE
Support for media keys while screen is locked

### ISSUE THREAD

**Issue by nenad** [Raymo111/i3lock-color#85]
Would be super useful to be able to play/pause while the screen is locked. There is [already a patch for that](https://aur.archlinux.org/packages/i3lock-media-keys/) so implementing would be a breeze. I don't know how you feel about allowing the keys from a security perspective, but in my opinion, the pros > the cons of this.

**Comment by PandorasFox** [comment]
I'll probably pull that patch into Dev tomorrow, and probably sit down and do a few of the other issues.

I hasn't been aware that existed - thanks!

As for the security.... Ehhh, I think that the utility outweighs the cons. It's off by default but adds the extra usability if desired.

I'm kinda of the opinion that if a bug requires someone to, say, compromise a media player/hijack the media keys behind the locker and require a physical keypress... They're probably determined enough to get around it anyways. (Realistically, if someone has that level of control, there's nothing stopping them from just sticking something to listen on a port and then kill your screenlocker when you poke that port, or something to that effect...)

Security is nice, but physical access is total access anyways :) This shouldn't make the screen locker like, crash for any reason since sending a single XCB event is pretty safe, so... Yeah :)

**Comment by PandorasFox** [comment]
This is in dev now @ 9c3eaaf2f3b66df7c27609da0fa76fbc0bae2888. Seems to work fine for me, but I'll push it out with the next set of changes.

**Comment by nenad** [comment]
Beautiful, thank you!

I'll close the issue and wait for this to arrive to master :smile:
